# -*- coding: utf-8 -*-
"""EDA Lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZhrrfAg-1WqAByBDVQxAppXSaRGcpgV
"""

import pandas as pd

df = pd.read_excel('student_working_hour_data.xlsx')
df.head()

# Sleep
sleep = df.iloc[:,2]

sleep.mean()

sleep.mode()

sleep.median()

sleep.var()

sleep.std()

sleep.quantile([0.25,0.5,0.75])

